### ISSUE TITLE
Unable to build on MacOS Ventura

### ISSUE THREAD

**Issue by Kuchiru** [webosbrew/youtube-webos#107]
Hi, as the app has had quite some fixes since the last release i attempted to build a more recent version.
Unfortunately it failed.

```
youtube-webos % npm run build && npm run package

> youtube-webos@0.0.2 build
> webpack

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (/Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/NormalModule.js:936:10)
    at /Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/NormalModule.js:745:11)
    at /Users/jo_and_jo/Documents/youtube-webos/node_modules/webpack/lib/NormalModule.js:809:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.3.0
```

**Comment by Kuchiru** [comment]
update: fixed this with `NODE_OPTIONS=--openssl-legacy-provider npm run build && npm run package`
