### ISSUE TITLE
Bug: ares-install fails with  rm: can't remove '/media/developer/temp': Permission denied

### ISSUE THREAD

**Issue by zozidalom** [webosbrew/youtube-webos#230]
48inch LG OLED TV
Software version: 03.41.05

## Issue description

` ares-install -d livingroom youtube.leanback.v4_0.3.4_all.ipk`

ares-install ERR! [ssh exec failure]: Command '/bin/rm -rf /media/developer/temp && /bin/mkdir -p /media/developer/temp' exited with code=1
ares-install ERR! [ssh exec failure]: (Original Message: rm: can't remove '/media/developer/temp': Permission denied)

**Comment by zozidalom** [comment]
```
ares-install ERR! [ssh exec failure]: Command '/bin/rm -rf /media/developer/temp && /bin/mkdir -p /media/developer/temp' exited with code=1
ares-install ERR! [ssh exec failure]: (Original Message: rm: can't remove '/media/developer/temp': Permission denied)
ares-install verb Error
    at new CLIError (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\lib\base\error-handler.js:247:22)
    at errMsgHdlr.getErrMsg (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\lib\base\error-handler.js:172:32)
    at makeExecError (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\lib\base\novacom.js:53:28)
    at Channel.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\lib\base\novacom.js:902:27)
    at Channel.emit (node:events:518:28)
    at SSH2Stream.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\node_modules\ssh2\lib\Channel.js:210:14)
    at SSH2Stream.emit (node:events:518:28)
    at parse_CHANNEL_REQUEST (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\node_modules\ssh2-streams\lib\ssh.js:4467:8)
    at parsePacket (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\node_modules\ssh2-streams\lib\ssh.js:3768:12)
    at SSH2Stream._transform (C:\Users\user\AppData\Roaming\npm\node_modules\@webosose\ares-cli\node_modules\ssh2-streams\lib\ssh.js:701:13)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:572:12)
    at _write (node:internal/streams/writable:501:10)
    at Writable.write (node:internal/streams/writable:510:10)
    at Socket.ondata (node:internal/streams/readable:1009:22)
    at Socket.emit (node:events:518:28)
ares-install verb novacom#Session()#begin() clear Session
ares-install info novacom#Session()#end() user-requested termination
```

Here are the full logs with -v flag. I tested on 2 different TV's 0/2.

**Comment by Tammura** [comment]
@zozidalom did you find any solution?

**Comment by zozidalom** [comment]
@Tammura It's a long way since this, but I think  the solution was, to install it via developer mode + webos-homebrew-channel for me
